### ISSUE TITLE
0.8.3 meteor

### ISSUE THREAD

**Issue by tejasmanohar** [tsega/meteor-bootstrap3-lightbox#1]
Does this work with 0.8.3 meteor? If not, can I make it work by installing an older version?

**Comment by tsega** [comment]
@tejas-manohar I'm sorry to say but the package has been updated for use with the new meteor packaging system. 

I would also recommend that you upgrade both [your base meteor installation and your app packages](https://hackpad.com/Migrating-Apps-UfPrM192vSQ). After that you can easily add this package.
