### ISSUE TITLE
This is not working with Meteor 1.2

### ISSUE THREAD

**Issue by maitrid** [tsega/meteor-bootstrap3-lightbox#3]
I added the package as indicated, and added in test code in the fashion according to the instructions, and  the image for the href simply goes to a different page on the browser.  If i use a web page URL, the lightbox shows up, but the content is just this message: 'Could not detect remote target type. Force the type using data-type="image|youtube|vimeo"'. 

The Meteor version is 1.2.0.2, and the Bootstrap version is twbs:bootstrap  3.3.5.

**Comment by tsega** [comment]
@maitrid  the answer is actually right there in the error message, you need to add the attribute `data-type='image'` to the target `a` tag. Take a look at an example [meteor pad](http://app-7cga5nlv.meteorpad.com/).
